// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dosxkpummvyibqgpnetn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRvc3hrcHVtbXZ5aWJxZ3BuZXRuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAyMzI1OTQsImV4cCI6MjA2NTgwODU5NH0.EzKSR2uPLNXX1NUG0jZRbG_95QVh5hvzWDR_rgG4up0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);